---
--- Generated by Luanalysis
--- Created by nori.
--- DateTime: 11/30/21 3:52 PM
---
numbers = {}

for i= 1,100 do
    numbers[i] = i-1
end

for i, v2 in ipairs(numbers) do
   print("Index: " .. i," Inhalt", v2)
end